### ISSUE TITLE
Rule doesn't work as expected

### ISSUE THREAD

**Issue by putuyoga** [Gillespie59/eslint-plugin-angular#430] opened 2016-12-28 08:36 UTC
It seems that the rule doesn't work. i use config from `eslint-config-angular` Still can't figure it why. here is my .estlintrc
```{
  "extends": ["angular"],
  "ecmaFeatures": {
        "blockBindings": true
  },
  "indent": ["error", 2],
  "env": {
    "browser": true,
    "jasmine": true
  },
  "globals": {
    "angular": true,
    "module": true,
    "inject": true
  }
}
```

and here is my controller look like: 
```
    const controllerId = 'UserController';

    angular.module('inspinia')
        .controller(controllerId, UserController);

    UserController.$inject = ['UserService', '$compile', '$scope', '$q', 'CommonEnum', 'CommonService', '$uibModal', 'TenantService'];

    function UserController(UserService, $compile, $scope, $q, CommonEnum, CommonService, $uibModal, TenantService) {

        $scope.myform = {};
        $scope.UserList = [];
        $scope.errorMessage = {
            isError: '',
            message: ''
        }
        $scope.showLoadingOnTable = false;
        $scope.TenantId = '';

        $scope.findAll = function() {

            $scope.showLoadingOnTable = true;
            var request = {
                TenantId: $scope.TenantId
            }
            UserService.FindAllByTenantId(request)
                .then(function(response) {
                    $scope.UserList = response.data.Model;
                    $scope.showLoadingOnTable = false;
                })
                .catch(function(error) {
                    var response = CommonService.getErrorMessage(error);
                    $scope.errorMessage = {
                        isError: true,
                        message: response.message
                    }
                    $scope.showLoadingOnTable = false;
                });
        }
    }
```

it should trigger **controller_as** rule. But it didn't. Strange. Any advice?

**Comment by Gillespie59** [comment] 2016-12-31 13:08
It looks like the problem is the name of your controller defined in a variable. I am going to fix it.

**Comment by Gillespie59** [comment] 2016-12-31 13:20
I have just pushed a fix. Can you test your use case with the development branch ?

**Comment by putuyoga** [comment] 2017-01-04 04:14
It works now. Thanks!

**Closed** 2017-03-19 15:33 UTC
Labels: Bug, Improvement, Rule, waiting-feedback
