### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by albertosantini** [Gillespie59/eslint-plugin-angular#103] opened 2015-06-06 12:00 UTC
With 0.0.8 (and eslint 0.22.1)

```
$ cat app.module.js
"use strict";

angular
    .module("argo", [
        "ngMaterial",
        "ui.router",
        "ngSocket",
        "LocalStorageModule"
    ]);

$ eslint app.module.js
C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint-plugin-angular\rules\utils\utils.js:68
                        return node.arguments.length === 2 && this.isLiteralType(node.arguments[0])
                                             ^
TypeError: Cannot read property 'length' of undefined
    at Object.module.exports.isAngularComponent (C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint-plugin-angular\rules\utils\utils.js:68:25)
    at EventEmitter.ExpressionStatement (C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint-plugin-angular\rules\ng_module_getter.js:13:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint\lib\eslint.js:725:25)
    at Controller.__execute (C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:393:31)
    at Controller.traverse (C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint\node_modules\estraverse\estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint\lib\eslint.js:718:24)
    at processFile (C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:197:27)
    at C:\Users\icebox\AppData\Roaming\npm\node_modules\eslint\lib\cli-engine.js:332:26
$
```

**Comment by Gillespie59** [comment] 2015-06-06 15:51
It looks like the problem come fro the carriage return. I will have a look.

**Comment by albertosantini** [comment] 2015-06-06 17:06
I don't think so.

I saved the file with unix line endings and the result is the same.

**Comment by mattlewis92** [comment] 2015-06-08 07:49
I'm getting the same error with my project. It looks like it's being caused by `'use strict';`. When outputting the value of `node` passed to the `isAngularComponent` function I get this:
```
{ type: 'Literal',
  value: 'use strict',
  raw: '\'use strict\'',
  range: [ 0, 12 ],
  loc: { start: { line: 1, column: 0 }, end: { line: 1, column: 12 } } }
```

**Comment by albertosantini** [comment] 2015-06-08 08:02
Confirmed. it is `"use strict";`.

After removing it

```
$ eslint app.module.js                                                                                  
                                                                                                        
app.module.js                                                                                           
  1:0  error  Use the global form of "use strict"                                     strict            
  1:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_
getter                                                                                                  
                                                                                                        
✖ 2 problems (2 errors, 0 warnings)                                                                     

```

@mattlewis92 Nice catch! :)

**Comment by twDuke** [comment] 2015-06-08 16:14
Same issue here with the same versions.

**Comment by Gillespie59** [comment] 2015-06-08 18:46
I have just push a fix. Can you test your project with the code hosted on the 0.0.9 branch ?

**Comment by albertosantini** [comment] 2015-06-08 20:01
Well testing on Argo, the snippet is ok, but other files display always the initial TypeError message.
 
About the second error `Avoid using a variable and instead use chaining ...` above, do you think it is correct? It seems to me Y022 is fulfilled.

**Comment by Gillespie59** [comment] 2015-06-08 20:46
I have reproduced this issue in my unit test. I am going to solve it tonight or tomortow

**Comment by Gillespie59** [comment] 2015-06-08 20:53
I think I solved this issue. Can you test again the 0.0.9 branch ? 

@albertosantini  : You talk about some more TypeError errors ? Can you give me more informations ? Thanks.

**Comment by mattlewis92** [comment] 2015-06-08 21:07
I'm still getting 
`Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter`
with the latest 0.0.9 branch. Example code:
```
'use strict';

angular
  .module('mwl.calendar')
  .controller('MwlElementDimensionsCtrl', function($element, $scope, $parse, $attrs) {

    $parse($attrs.mwlElementDimensions).assign($scope, {
      width: $element[0].offsetWidth,
      height: $element[0].offsetHeight
    });

  })
  .directive('mwlElementDimensions', function() {

    return {
      restrict: 'A',
      controller: 'MwlElementDimensionsCtrl'
    };

  });
```

**Comment by Gillespie59** [comment] 2015-06-08 21:12
OK I did not add this code into my tests. Will add it right now, and try to solve it.

**Comment by Gillespie59** [comment] 2015-06-08 21:18
The problem come with the `directive` call. will try to solve this issue with a recursive call.

**Comment by Gillespie59** [comment] 2015-06-08 21:27
Another update ;)

Can you test again ? Thanks a lot

**Comment by mattlewis92** [comment] 2015-06-08 21:39
Now it's throwing an error again:
```
/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint-plugin-angular/rules/ng_module_getter.js:14
                while(calleeObject.type === 'CallExpression' && !utils.isAngul
                                                             ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.ExpressionStatement (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint-plugin-angular/rules/ng_module_getter.js:14:62)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/lib/eslint.js:725:25)
    at Controller.__execute (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/lib/eslint.js:718:24)
    at verify (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/index.js:21:25)
    at DestroyableTransform._transform (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/index.js:44:18)
    at DestroyableTransform.Transform._read (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
```

**Comment by Gillespie59** [comment] 2015-06-08 21:44
I have pushed a test for undefined value.

**Comment by mattlewis92** [comment] 2015-06-08 21:49
Same issue, different line:
```
/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint-plugin-angular/rules/ng_module_getter.js:18
                if (!(calleeObject.type === 'CallExpression' && utils.isAngula
                                  ^
TypeError: Cannot read property 'type' of undefined
    at EventEmitter.ExpressionStatement (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint-plugin-angular/rules/ng_module_getter.js:18:35)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at Controller.controller.traverse.enter (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/lib/eslint.js:725:25)
    at Controller.__execute (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/node_modules/estraverse/estraverse.js:393:31)
    at Controller.traverse (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/node_modules/estraverse/estraverse.js:491:28)
    at EventEmitter.module.exports.api.verify (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/eslint/lib/eslint.js:718:24)
    at verify (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/index.js:21:25)
    at DestroyableTransform._transform (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/index.js:44:18)
    at DestroyableTransform.Transform._read (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/mattlewis/Sites/angular-bootstrap-calendar/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
```

**Comment by Gillespie59** [comment] 2015-06-08 21:51
Why we do not have this kind of syntax of JS ( ?. ) in order to manage undefined value ;)

**Comment by mattlewis92** [comment] 2015-06-08 22:00
That fixed the error but I'm getting the `angular/ng_module_getter` error again for a few files (It looks like the $on in the controller is causing it):
```
'use strict';

angular
  .module('mwl.calendar')
  .controller('MwlCalendarDayCtrl', function($scope) {

    $scope.$on('calendar.refreshView', function() {
    });

  })
  .directive('mwlCalendarDay', function() {

    return {
      templateUrl: 'src/templates/calendarDayView.html',
      restrict: 'EA',
      require: '^mwlCalendar',
      scope: {
        events: '=',
        currentDay: '=',
        onEventClick: '=',
        onEventDrop: '=',
        dayViewStart: '=',
        dayViewEnd: '=',
        dayViewSplit: '='
      },
      controller: 'MwlCalendarDayCtrl as vm'
    };

  });
```

**Comment by mattlewis92** [comment] 2015-06-08 22:01
This is the project I'm testing your branch against by the way, which should save a bit of back and forth :)
https://github.com/mattlewis92/angular-bootstrap-calendar

**Comment by albertosantini** [comment] 2015-06-09 07:00
I second @mattlewis92's suggestion about back and forth. :)

https://github.com/albertosantini/argo

**Comment by albertosantini** [comment] 2015-06-11 08:25
With the latest commits in 0.0.9 branch (f847851), I linted again Argo.

There is not the Type Error, but there is annoying angular/ng_module_getter error, especially in the tests: it seems for every `describe` or `it` call.

```
$ grunt
Running "eslint:src" (eslint) task

src/client/app/components/charts.directive.js
   34:12  error  Avoid using a variable and instead use chaining with the getter syntax
                 angular/ng_module_getter
   34:12  error  The "$watch" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/ng_on_watch
   48:12  error  The "$watch" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/ng_on_watch
  234:16  error  Avoid using a variable and instead use chaining with the getter syntax
                 angular/ng_module_getter

src/client/app/components/dualcolor.directive.js
  18:12  error  The "$watch" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/ng_on_watch

src/client/app/components/highlighter.directive.js
  18:12  error  The "$watch" call should be assigned to a variable, in order to be destroyed during the $destroy event  angular/ng_on_watch

src/client/app/header/header.js
  108:24  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/accounts.service.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  62:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  63:8  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/activity.service.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  58:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  59:8  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/app.module.spec.js
  3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  4:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/app.routes.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  17:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/exposure.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  32:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  42:8  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/orders.service.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  69:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  70:8  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/positions.service.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  57:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  58:8  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/quotes.service.spec.js
   4:0   error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  22:12  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  37:4   error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  38:8   error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/session.service.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  11:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  24:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  42:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

src/client/test/specs/trades.service.spec.js
   3:0  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  63:4  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter
  64:8  error  Avoid using a variable and instead use chaining with the getter syntax  angular/ng_module_getter

✖ 37 problems (37 errors, 0 warnings)

```

**Comment by albertosantini** [comment] 2015-06-11 08:27
Do you prefer I close this issue on Type Error and open new issue on ng_module_getter?

**Comment by Gillespie59** [comment] 2015-06-14 09:11
Hi guys. 

We can keep like that. 

I will clone your projecct, and test the plugin on both of them. 

Sorry  for the delay 

Manu

**Comment by Gillespie59** [comment] 2015-06-14 10:03
Hi @albertosantini  and @mattlewis92 

I have just pushed a fix, thanks to your projects I used for my tests ;)

When I lint your project, I do not have any more problems. 

Can you test on your side ?  If it is ok for you, I will create the 0.0.9 release. 

Thanks 

Manu

**Comment by albertosantini** [comment] 2015-06-14 11:10
@Gillespie59 Thanks a lot for the effort.

For me it is ok.

**Comment by Gillespie59** [comment] 2015-06-14 11:17
@albertosantini  great news !:d

**Comment by mattlewis92** [comment] 2015-06-15 07:51
Just tested it and it's all working for me :)

**Comment by Gillespie59** [comment] 2015-06-15 15:39
0.0.9 released. 
Thanks

**Closed by Gillespie59** 2015-06-15 15:39 UTC
Labels: Bug

**Comment by mattlewis92** [comment] 2015-06-15 15:44
Great stuff, can you publish 0.0.9 npm as well please!

**Comment by Gillespie59** [comment] 2015-06-15 17:07
Oops. I forgot. Long day today. I will do in few minutes

**Comment by Gillespie59** [comment] 2015-06-15 18:06
NPM release done
